from pickle import TRUE


VIACEP_URL = "https://viacep.com.br/ws"
BRASILAPI_URL = "https://brasilapi.com.br/api"

DB_PATH = "databases/database.db"

CACHE_ENABLE = True
CACHE_EXPIRE = 60
CACHE_PREFIX = "pycep"

DAYS_TO_UPDATE = 30

ADMIN_COOKIE_NAME = "admin_auth"
ADMIN_COOKIE_DOMAIN = "localhost"
ADMIN_COOKIE_HTTPONLY = TRUE
ADMIN_COOKIE_SAMESITE = "lax"
ADMIN_COOKIE_SECURE = TRUE
ADMIN_COOKIE_MAX_AGE = 60

USER_COOKIE_NAME = "user_auth"
USER_COOKIE_DOMAIN = "localhost"
USER_COOKIE_HTTPONLY = TRUE
USER_COOKIE_SAMESITE = "lax"
USER_COOKIE_SECURE = TRUE
USER_COOKIE_MAX_AGE = 60

JWT_SECRET = "6ea56ab82f19a18350d255696f9060b77204d9d427ce5c31910f04115b61a604"
JWT_ALGORITHM = "HS256"
JWT_EXPIRE_MINUTES = 3600